[
    [
        [
            [
                [
                    [
                        [[DF,EF,CF]]
                    ],
                    [
                        [[BE,CF,DF],[DE,CF,DF],[DE,BE,DF],[DE,BE,CF]]
                    ]
                ],
                [
                    [
                        [[AD,CF,EF],[DE,CF,EF],[DE,AD,EF],[DE,AD,CF]]
                    ],
                    [
                        [[AD,BE,CF]]
                    ]
                ]
            ],
            [
                [
                    [
                        [[BC,EF,DF],[AC,EF,DF],[AC,BC,DF],[AC,BC,EF]]
                    ],
                    [
                        [[BE,DE,DF],[BC,DE,DF],[BC,BE,DF],[BC,BE,DE],[AC,DE,DF],[AC,BE,DF],[AC,BE,DE],[AC,BC,DF],[AC,BC,DE],[AC,BC,BE]]
                    ]
                ],
                [
                    [
                        [[AD,DE,EF],[AC,DE,EF],[AC,AD,EF],[AC,AD,DE],[BC,DE,EF],[BC,AD,EF],[BC,AD,DE],[BC,AC,EF],[BC,AC,DE],[BC,AC,AD]]
                    ],
                    [
                        [[AD,BE,BC],[AC,BE,BC],[AC,AD,BC],[AC,AD,BE]]
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        [[BC,AB,BE],[DF,EF,CF]]
                    ],
                    [
                        [[CF,DF,DE],[BC,DF,DE],[BC,CF,DE],[BC,CF,DF],[AB,DF,DE],[AB,CF,DE],[AB,CF,DF],[AB,BC,DE],[AB,BC,DF],[AB,BC,CF]]
                    ]
                ],
                [
                    [
                        [[BC,AB,BE],[AD,CF,CB],[AB,CF,CB],[AB,AD,CB],[AB,AD,CF],[DE,EF,BE],[AD,CF,EF],[DE,CF,EF],[DE,AD,EF],[DE,AD,CF]]
                    ],
                    [
                        [[AD,CF,CB],[AB,CF,CB],[AB,AD,CB],[AB,AD,CF]]
                    ]
                ]
            ],
            [
                [
                    [
                        [[BE,EF,DF],[AB,EF,DF],[AB,BE,DF],[AB,BE,EF],[AC,EF,DF],[AC,BE,DF],[AC,BE,EF],[AC,AB,DF],[AC,AB,EF],[AC,AB,BE]]
                    ],
                    [
                        [[AC,DF,DE],[AB,DF,DE],[AB,AC,DE],[AB,AC,DF]]
                    ]
                ],
                [
                    [
                        [[AB,AC,AD],[DE,EF,BE]]
                    ],
                    [
                        [[AB,AC,AD]]
                    ]
                ]
            ]
        ]
    ],
    [
        [
            [
                [
                    [
                        [[AB,AC,AD],[DF,EF,CF]]
                    ],
                    [
                        [[AB,AC,AD],[BE,CF,AC],[AB,CF,AC],[AB,BE,AC],[AB,BE,CF],[DE,DF,AD],[BE,CF,DF],[DE,CF,DF],[DE,BE,DF],[DE,BE,CF]]
                    ]
                ],
                [
                    [
                        [[CF,EF,DE],[AC,EF,DE],[AC,CF,DE],[AC,CF,EF],[AB,EF,DE],[AB,CF,DE],[AB,CF,EF],[AB,AC,DE],[AB,AC,EF],[AB,AC,CF]]
                    ],
                    [
                        [[BE,CF,AC],[AB,CF,AC],[AB,BE,AC],[AB,BE,CF]]
                    ]
                ]
            ],
            [
                [
                    [
                        [[AD,DF,EF],[BA,DF,EF],[BA,AD,EF],[BA,AD,DF],[BC,DF,EF],[BC,AD,EF],[BC,AD,DF],[BC,BA,EF],[BC,BA,DF],[BC,BA,AD]]
                    ],
                    [
                        [[BC,AB,BE],[DE,DF,AD]]
                    ]
                ],
                [
                    [
                        [[BA,DE,EF],[BC,DE,EF],[BC,BA,EF],[BC,BA,DE]]
                    ],
                    [
                        [[BC,AB,BE]]
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        [[AC,BC,CF],[AD,BE,BC],[AC,BE,BC],[AC,AD,BC],[AC,AD,BE],[DF,EF,CF],[EF,AD,BE],[DF,AD,BE],[DF,EF,BE],[DF,EF,AD]]
                    ],
                    [
                        [[AC,BC,CF],[DE,DF,AD]]
                    ]
                ],
                [
                    [
                        [[AC,BC,CF],[DE,EF,BE]]
                    ],
                    [
                        [[AC,BC,CF]]
                    ]
                ]
            ],
            [
                [
                    [
                        [[EF,AD,BE],[DF,AD,BE],[DF,EF,BE],[DF,EF,AD]]
                    ],
                    [
                        [[DE,DF,AD]]
                    ]
                ],
                [
                    [
                        [[DE,EF,BE]]
                    ],
                    [
                        []
                    ]
                ]
            ]
        ]
    ]
]